CREATE TABLE GX_LOG_FIL
(
	LOG_DATE    VARCHAR2(8),
    LOG_SEQ     NUMBER,
	USER_NAME   VARCHAR2(15),
	OBJ_NAME    VARCHAR2(25),
	OBJ_TYPE    VARCHAR2(10),
	START_TIME  DATE,
    END_TIME    DATE,
    ACT_STATUS  VARCHAR2(1),
    LOG_MSG     CLOB         
);
COMMENT ON TABLE GX_LOG_FIL IS '例程执行日志';
COMMENT ON COLUMN GX_LOG_FIL.LOG_DATE IS '日志日期';    
COMMENT ON COLUMN GX_LOG_FIL.LOG_SEQ IS '日志序号';
COMMENT ON COLUMN GX_LOG_FIL.USER_NAME IS '执行用户名'; 
COMMENT ON COLUMN GX_LOG_FIL.OBJ_NAME IS '例程名';  
COMMENT ON COLUMN GX_LOG_FIL.OBJ_TYPE IS '例程类型';  
COMMENT ON COLUMN GX_LOG_FIL.START_TIME IS '例程开始执行时间';
COMMENT ON COLUMN GX_LOG_FIL.END_TIME IS '例程结束执行时间';  
COMMENT ON COLUMN GX_LOG_FIL.ACT_STATUS IS '例程执行状态：0 - 执行中,1 - 成功,2 - 失败';
COMMENT ON COLUMN GX_LOG_FIL.LOG_MSG IS '日志详细信息';   




CREATE SEQUENCE GX_SEQ_LOG 
      INCREMENT BY 1
          START WITH 10001
       MAXVALUE 999999
          CYCLE;

